### ISSUE TITLE
TLD not supported by registrar

### ISSUE THREAD

**Issue by wulfsystems** [openprovider/openprovider-domains-blesta#19]
Since 5.2 I cant add new tld to my packages...
I tried with tld "pl" and "online"
![Bildschirmfoto von 2021-10-30 21-47-37](https://user-images.githubusercontent.com/84345842/139556668-bab0bef8-2b98-484a-a43b-fb52d9b50b0b.png)

**Comment by wmetge** [comment]
@wulfsystems we are working on a fix. It seems that Blesta added a "supoprted TLD" method for registrar modules which wasn't included in the previous release.

**Comment by wulfsystems** [comment]
@wmetge Is there a timeline?

**Comment by wmetge** [comment]
@wulfsystems, the latest commits should solve the issue. Thank you for your patience
