### ISSUE TITLE
Incompatible with Blesta 5.2.2

### ISSUE THREAD

**Issue by wulfsystems** [openprovider/openprovider-domains-blesta#20]
Cant add new TLD....
"The provided TLD is unsupported by the selected registrar module."

**Comment by wmetge** [comment]
could you tell us which TLD?

**Comment by wulfsystems** [comment]
.immo

**Comment by wmetge** [comment]
Thank you for bringing this to our attention. The readme has been updated with [instructions for adding TLDs](https://github.com/openprovider/openprovider-domains-blesta/blob/main/openprovider/config/openprovider.php)
